services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestion-gastos:latest
    container_name: gestion-gastos
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mysql://mysql:3306/gestion_gastos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASS: "Frebian2020#$"
      PORT: "8081"
    networks:
      - mysql-net
      - app-network
networks:
  mysql-net:
    external: true
  app-network:
    external: true